### ISSUE TITLE
Trouble Authorizing

### ISSUE THREAD

**Issue by OIK2** [jaymoulin/docker-google-musicmanager#2]
When I attempt to authorize using "docker exec -ti googlemusicmanager auth" I get the following error message: 
`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"auth\": executable file not found in $PATH"`

I have added both /media/library as well as the long form of the location of my library to the path.

**Comment by jaymoulin** [comment]
Fixed in 0.2.1. just `docker rm -f googlemusicmanager && docker pull jaymoulin/rpi-google-musicmanager` before creating your container again to be sure to have this fix.
