### ISSUE TITLE
Error on execute google auth

### ISSUE THREAD

**Issue by fanningert** [jaymoulin/docker-google-musicmanager#6]
Hi, I tested your docker container (latest) and get following error message.

```
oci runtime error: exec failed: container_linux.go:265: starting container process caused "exec: \"auth\": executable file not found in $PATH"
``` 

I get the same message, when I execute
```
docker exec -i -t google-musicmanager /bin/bash
```

I running the docker engine version 17.09.1-ce on unRaid 6.4.0.

Other docker images running perfectly on this docker engine.

**Comment by jaymoulin** [comment]
Should be fixed on latest release (0.6.2)
